Delete DOS binary files in samples folder except utils.obj because when compile utils.c it have "..\utils.c(144): Error! E1010: Type mismatch"
Signed-off-by: Khral Steelforge <garuda2550@gmail.com>